
/**************************************************************
 *	
 *	backgroundMusic, 8 bit, 11025Hz,
 *	1 channel, 366704 bytes/channel
 *	Total Size: 1 * 366704 + 4 (header) = 366748 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard\Documents\GBA Emulator\backgroundMusic.wav
 *	Time-stamp: Thu May 19 15:25:59 2016
 *	
 **************************************************************/

#ifndef __BACKGROUNDMUSICH__
#define __BACKGROUNDMUSICH__

#define BACKGROUNDMUSICFREQ 11025
#define BACKGROUNDMUSICLEN 366704

extern const unsigned char backgroundMusic[366704];

#endif /* __BACKGROUNDMUSICH__ */
