
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 419919 bytes/channel
 *	Total Size: 1 * 419919 + 4 (header) = 419963 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard Valentine\Documents\cs2261\Homework\HW06_RichardValentine\GameSong.wav
 *	Time-stamp: Tue Oct 07 18:36:05 2014
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 419919

extern const unsigned char GameSong[419919];

#endif /* __GAMESONGH__ */
