
/**************************************************************
 *	
 *	injuredGrunt, 8 bit, 11025Hz,
 *	1 channel, 2277 bytes/channel
 *	Total Size: 1 * 2277 + 4 (header) = 2321 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard Valentine\Documents\cs2261\Final Project\injuredGrunt.wav
 *	Time-stamp: Fri Nov 28 21:57:18 2014
 *	
 **************************************************************/

#ifndef __INJUREDGRUNTH__
#define __INJUREDGRUNTH__

#define INJUREDGRUNTFREQ 11025
#define INJUREDGRUNTLEN 2277

extern const unsigned char injuredGrunt[2277];

#endif /* __INJUREDGRUNTH__ */
