
/**************************************************************
 *	
 *	loseMusic, 8 bit, 11025Hz,
 *	1 channel, 423648 bytes/channel
 *	Total Size: 1 * 423648 + 4 (header) = 423692 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard Valentine\Documents\cs2261\Final Project\loseMusic.wav
 *	Time-stamp: Tue Nov 04 18:25:12 2014
 *	
 **************************************************************/

#ifndef __LOSEMUSICH__
#define __LOSEMUSICH__

#define LOSEMUSICFREQ 11025
#define LOSEMUSICLEN 423648

extern const unsigned char loseMusic[423648];

#endif /* __LOSEMUSICH__ */
