
/**************************************************************
 *	
 *	menuMusic, 8 bit, 44100Hz,
 *	1 channel, 907337 bytes/channel
 *	Total Size: 1 * 907337 + 4 (header) = 907381 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard\Documents\GBA Emulator\menuMusic.wav
 *	Time-stamp: Thu May 19 15:01:40 2016
 *	
 **************************************************************/

#ifndef __MENUMUSICH__
#define __MENUMUSICH__

#define MENUMUSICFREQ 44100
#define MENUMUSICLEN 907337

extern const unsigned char menuMusic[907337];

#endif /* __MENUMUSICH__ */
