
/**************************************************************
 *	
 *	slash, 8 bit, 11025Hz,
 *	1 channel, 2888 bytes/channel
 *	Total Size: 1 * 2888 + 4 (header) = 2932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard Valentine\Documents\cs2261\Final Project\slash.wav
 *	Time-stamp: Tue Nov 04 19:07:36 2014
 *	
 **************************************************************/

#ifndef __SLASHH__
#define __SLASHH__

#define SLASHFREQ 11025
#define SLASHLEN 2888

extern const unsigned char slash[2888];

#endif /* __SLASHH__ */
