
/**************************************************************
 *	
 *	winMusic, 8 bit, 11025Hz,
 *	1 channel, 75168 bytes/channel
 *	Total Size: 1 * 75168 + 4 (header) = 75212 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Richard Valentine\Documents\cs2261\Final Project\winMusic.wav
 *	Time-stamp: Tue Nov 04 18:53:26 2014
 *	
 **************************************************************/

#ifndef __WINMUSICH__
#define __WINMUSICH__

#define WINMUSICFREQ 11025
#define WINMUSICLEN 75168

extern const unsigned char winMusic[75168];

#endif /* __WINMUSICH__ */
